### PR TITLE
Check if Tracer is on classpath

### LINKED ISSUE #542: riptide-spring-boot-starter vs. tracing-lightstep-spring-boot-starter
## Description
In a project, I'm using the `riptide-spring-boot-starter` without [Tracer](https://github.com/zalando/tracer) integration. When I included `tracing-lightstep-spring-boot-starter` my app failed to start with the following exception:

    java.lang.NoClassDefFoundError: org/zalando/tracer/concurrent/TracingExecutors
	at org.zalando.riptide.spring.DefaultRiptideRegistrar.trace(DefaultRiptideRegistrar.java:378) ~[riptide-spring-boot-starter-2.10.1.jar:na]
	at org.zalando.riptide.spring.DefaultRiptideRegistrar.registerExecutor(DefaultRiptideRegistrar.java:102) ~[riptide-spring-boot-starter-2.10.1.jar:na]
	at org.zalando.riptide.spring.DefaultRiptideRegistrar.lambda$registerAsyncClientHttpRequestFactory$1(DefaultRiptideRegistrar.java:94) ~[riptide-spring-boot-starter-2.10.1.jar:na]
	at org.zalando.riptide.spring.Registry.registerIfAbsent(Registry.java:72) ~[riptide-spring-boot-starter-2.10.1.jar:na]
	at org.zalando.riptide.spring.DefaultRiptideRegistrar.registerAsyncClientHttpRequestFactory(DefaultRiptideRegistrar.java:85) ~[riptide-spring-boot-starter-2.10.1.jar:na]
	at org.zalando.riptide.spring.DefaultRiptideRegistrar.lambda$register$0(DefaultRiptideRegistrar.java:73) ~[riptide-spring-boot-starter-2.10.1.jar:na]
	at com.google.common.collect.SingletonImmutableBiMap.forEach(SingletonImmutableBiMap.java:65) ~[guava-27.0-jre.jar:na]
	at org.zalando.riptide.spring.DefaultRiptideRegistrar.register(DefaultRiptideRegistrar.java:72) ~[riptide-spring-boot-starter-2.10.1.jar:na]
	at org.zalando.riptide.spring.RiptidePostProcessor.postProcessBeanDefinitionRegistry(RiptidePostProcessor.java:47) ~[riptide-spring-boot-starter-2.10.1.jar:na]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:125) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:691) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:528) ~[spring-context-5.1.3.RELEASE.jar:5.1.3.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]

The [offending part](https://github.com/zalando/riptide/blob/ea91da2c6a9f899f1bab2499aa3a29b08ae7186f/riptide-spring-boot-starter/src/main/java/org/zalando/riptide/spring/DefaultRiptideRegistrar.java#L397) of the code is:
```java
private BeanMetadataElement trace(final String executor) {
    if (registry.isRegistered("tracer")) {
        return genericBeanDefinition(TracingExecutors.class)
                .setFactoryMethod("preserve")
                .addConstructorArgReference(executor)
                .addConstructorArgReference("tracer")
                .getBeanDefinition();
    } else {
        return ref(executor);
    }
}
```

The opentracing autoconfiguration adds a bean called "tracer" to the context.  As soon as there is any bean with the name "tracer" available, Riptide will try to configure its clients to use it. However the Riptide-Tracer is not compatible with the OpenTracing Tracer and leads to that exception. 

## Expected Behavior
Riptide should not confuse the OpenTracing tracer with its own one.

## Possible Fix
Instead of referencing beans by name, Riptide should try to fetch them by type and probably also check if the class is available.

## Context
Using both Riptide and OpenTracing in the same project and while making use of the auto-configuration.

## Your Environment
* Version used:
  ```
  <riptide.version>2.10.1</riptide.version>
  <tracing-lightstep-spring-boot-starter.version>0.1.0</tracing-lightstep-spring-boot-starter.version>
  ```
* Link to your project: internal

### PR DESCRIPTION
**Pull request by harti2006**
Try to auto-configure `Tracer` only if it is available on the class path.

## Motivation and Context
Fixes #542 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] I have added tests to cover my changes.

### CODE REVIEW

File: riptide-spring-boot-starter/src/main/java/org/zalando/riptide/spring/DefaultRiptideRegistrar.java [hunk 1]
```diff
@@ -60,6 +61,13 @@
 @AllArgsConstructor
 final class DefaultRiptideRegistrar implements RiptideRegistrar {
 
+    private static final boolean TRACER_PRESENT;
```
Comment (whiskeysierra) [inline riptide-spring-boot-starter/src/main/java/org/zalando/riptide/spring/DefaultRiptideRegistrar.java]: Can you use `Dependencies#ifPresent` instead? See usage within this class.

File: riptide-spring-boot-starter/src/main/java/org/zalando/riptide/spring/DefaultRiptideRegistrar.java [hunk 2]
```diff
@@ -394,15 +395,19 @@ private Tag clientName(final String id, final Client client) {
...
-        if (registry.isRegistered("tracer")) {
-            return genericBeanDefinition(TracingExecutors.class)
-                    .setFactoryMethod("preserve")
-                    .addConstructorArgReference(executor)
-                    .addConstructorArgReference("tracer")
-                    .getBeanDefinition();
-        } else {
-            return ref(executor);
-        }
+        final AtomicReference<BeanMetadataElement> result = new AtomicReference<>();
```
Comment (whiskeysierra) [inline riptide-spring-boot-starter/src/main/java/org/zalando/riptide/spring/DefaultRiptideRegistrar.java]: Ah, that's unfortunate. Can you implement a new version of `ifPresent`?

Signatures that I could imagine that would work:

- `<T> T ifPresent(String, Supplier<T>, Supplier<T>)`
- `<T> Optional<T>(String, Supplier<T>)`

That would remove the need for a stateful reference.

File: riptide-spring-boot-starter/src/main/java/org/zalando/riptide/spring/DefaultRiptideRegistrar.java [hunk 3]
```diff
@@ -394,15 +395,19 @@ private Tag clientName(final String id, final Client client) {
...
+
+        ifPresent("org.zalando.tracer.concurrent.TracingExecutors", () -> {
```
Comment (harti2006) [inline riptide-spring-boot-starter/src/main/java/org/zalando/riptide/spring/DefaultRiptideRegistrar.java]: Maybe it's prettier to expose a method `Dependencies#isPresent(String)` that simply returns a Boolean

Comment (whiskeysierra) [reply riptide-spring-boot-starter/src/main/java/org/zalando/riptide/spring/DefaultRiptideRegistrar.java]: I used the supplier version since that was easier to cover. But having both cases is already impossible to cover since you can't change the classpath during tests...

File: riptide-spring-boot-starter/src/main/java/org/zalando/riptide/spring/DefaultRiptideRegistrar.java [hunk 4]
```diff
@@ -395,19 +394,20 @@ private Tag clientName(final String id, final Client client) {
...
+        final Optional<BeanMetadataElement> result = ifPresent("org.zalando.tracer.concurrent.TracingExecutors",
+                () -> {
+                    if (registry.isRegistered("tracer")) {
+                        return genericBeanDefinition(TracingExecutors.class)
+                                .setFactoryMethod("preserve")
+                                .addConstructorArgReference(executor)
+                                .addConstructorArgReference("tracer")
+                                .getBeanDefinition();
+                    } else {
+                        return null;
```
Comment (whiskeysierra) [inline riptide-spring-boot-starter/src/main/java/org/zalando/riptide/spring/DefaultRiptideRegistrar.java]: I'd go with `ref(executor)` here. It's a different case. We have two fallbacks now: a) tracer not on the classpath and b) tracer not registered/configured.

Comment (harti2006) [reply riptide-spring-boot-starter/src/main/java/org/zalando/riptide/spring/DefaultRiptideRegistrar.java]: yes, I wanted to keep it DRY. The null returned here will lead to an empty Optional and trigger the fallback in line 410.

**Comment by harti2006** [comment]
@whiskeysierra rebase done. Test are green again. Do see anything that would block the PR from being merged?

**Comment by whiskeysierra** [comment]
:+1:

**Comment by whiskeysierra** [comment]
I'm releasing this (add some other features) as 2.11.0 to central.

Thanks for your contribution! :tada:
