### PR TITLE
Denied second captures

### LINKED ISSUE #292: Capture should deny second capture
Could throw an `IllegalStateException`

### PR DESCRIPTION
**Pull request by whiskeysierra**
Fixes #292

### CODE REVIEW

File: riptide-capture/src/main/java/org/zalando/riptide/capture/DefaultCapture.java [hunk 1]
```diff
@@ -19,8 +19,12 @@
 
     @Override
     public void tryAccept(@Nullable final T input) {
-        // TODO fail on second capture?
-        reference.compareAndSet(null, Optional.ofNullable(input));
+        final boolean captured = reference.compareAndSet(null, Optional.ofNullable(input));
+        final boolean alreadyCaptured = !captured;
```
Comment (AlexanderYastrebov) [inline riptide-capture/src/main/java/org/zalando/riptide/capture/DefaultCapture.java]: Not sure if this one improves readability, I would put negation into if condition

Comment (whiskeysierra) [reply riptide-capture/src/main/java/org/zalando/riptide/capture/DefaultCapture.java]: Done

**Comment by lukasniemeier-zalando** [comment]
:+1:
