### PR TITLE
Simplified exception handling for clients

### LINKED ISSUE #143: Replace IOException with UncheckedIOException?
@jhorstmann @lukasniemeier-zalando

### PR DESCRIPTION
**Pull request by whiskeysierra**
Fixes #143

### CODE REVIEW

File: riptide-core/src/test/java/org/zalando/riptide/IOTest.java [hunk 1]
```diff
@@ -92,10 +96,23 @@ public void shouldReadContributors() throws IOException, ExecutionException, Int
...
+
+        future.cancel(true);
+
+        try {
+            future.join();
+        } catch (final CancellationException e) {
+            // expected
+        }
+
+        driver.reset();
```
Comment (tkrop) [inline riptide-core/src/test/java/org/zalando/riptide/IOTest.java]: Shouldn't this be in `after()`?

**Comment by tkrop** [comment]
:+1:

File: riptide-core/src/test/java/org/zalando/riptide/IOTest.java (hunk 1 above)
Comment (whiskeysierra) [inline riptide-core/src/test/java/org/zalando/riptide/IOTest.java]: No. There is already a `server.verify()` in the teardown and we want to skip that because we're issuing a request that we want to cancel.

Comment (tkrop) [inline riptide-core/src/test/java/org/zalando/riptide/IOTest.java]: I can only see and `executor.shutdown()` ...

Anyhow, why do you need to reset at all? According to the theory you mentioned last week, it should run in an isolated test instance.
